# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sidewalkreator
                                 A QGIS plugin
 Plugin conceived to create the Geometries of Sidewalks (separated from streets) based on OpenStreetMap Streets, given a bounding polygon, outputting to JOSM format. It is mostly intended for acessibility Mapping. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-29
        copyright            : (C) 2021 by Kaue de Moraes Vestena
        email                : kauemv2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sidewalkreator class from file sidewalkreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from qgis.core import QgsApplication
    from .osm_sidewalkreator import sidewalkreator
    from .protoblock_provider import ProtoblockProvider

    # Initialize the main plugin
    plugin = sidewalkreator(iface)

    # Register the Processing provider
    # It's good practice to check if processing is available,
    # though for a plugin targeting modern QGIS, it usually is.
    try:
        from processing.core.Processing import Processing
        Processing.initialize() # Ensure Processing framework is initialized
        provider = ProtoblockProvider()
        QgsApplication.processingRegistry().addProvider(provider)
    except ImportError:
        # Handle case where processing might not be available (e.g., very old QGIS or specific setup)
        iface.messageBar().pushMessage("Warning", "Processing framework not available. SidewalKreator Processing tools will not be loaded.", level=1, duration=5) # Qgis.Warning is 1
    except Exception as e:
        # Catch any other exception during provider registration
        import sys
        iface.messageBar().pushMessage("Error", f"Could not register SidewalKreator Processing provider: {e}\n{sys.exc_info()}", level=2, duration=10) # Qgis.Critical is 2


    return plugin
