from itertools import cycle

l = [1,2,3,4,5,]

pool = cycle(l)

print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
print(next(pool))
