name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag for the release (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'The name of the release'
        required: true
        default: 'Release v1.0.0'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run release script
        run: python release/release_zip.py --output-dir ./release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/osm_sidewalkreator.zip
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
